### ISSUE TITLE
[Textures] Sectores Seguros incorrectos.

### ISSUE THREAD

**Issue by santiagosaied** [SlayerWx/Fox-s-Tale#1]
Descripcion: Hay sectores donde el personaje puede caminar libremente pero deberia de morir ya que se encuentra fuera de la plataforma. Se debe a la textura del suelo cuando el camino se encuentra de forma horizontal y se puede ver el latal hacia el agua.
Si nos posicionamos alli el personaje deberia caer al agua pero en este caso camina con libertad.

Video del Bug: [https://drive.google.com/file/d/1OuMPbMbqE-4rb4vLKuy9TZcgz0ty0hsm/view?usp=sharing](url)

**Comment by SlayerWx** [comment]
Arreglado! actualmente cambie como se generan estas plataformas y testeando un poco el bug, no vuelve a suceder.

no obstante no estoy al 100% seguro si puede volver a suceder o se me puede pasar por alto, si vuelve a encontrarse con este Bug sea libre de abrir nuevamente este hilo, Muchas gracias!
