### ISSUE TITLE
Wisp

### ISSUE THREAD

**Issue by lorenzopivotto** [SlayerWx/Fox-s-Tale#10]

**Comment by josmar37** [comment]
WispSpriteRenderer: Error enchequear, object is null. 

Se produce al crear muchos wisp a medida que se avanza por el juego.
•	Avanzar por el escenario
•	Se crean los wisp, sin control.
•	Detenerse, se empiezan a alejar.
•	Al volver a retornar el camino.
•	Produce el error al destruir el objeto en cantidad. 

Enlace:  https://drive.google.com/file/d/11qDr1e5d9xEbqKf2ygFqiRZ7K6HE74y_/view?usp=sharing
