### ISSUE TITLE
[Controls] Presionar direccion Durante pausa toma efecto al salir de ella

### ISSUE THREAD

**Issue by santiagosaied** [SlayerWx/Fox-s-Tale#2]
Descripcion: Al presionar P y  entrar en modo pausa, presionar cualquier tecla de movimiento provoca que al presionar P y salir de la pausa el personaje realice dicho movimiento.

Video: [https://drive.google.com/file/d/15bbVpSfxEb_rDVTUEmlYw9YhH7eFXr6R/view?usp=sharing](url)

**Comment by SlayerWx** [comment]
Arreglado!, en el próximo Build ya no estará este bug, muchas gracias por la ayuda!
