### ISSUE TITLE
[Ambient] Ballestas no matan al Player

### ISSUE THREAD

**Issue by santiagosaied** [SlayerWx/Fox-s-Tale#3]
Descripcion: En ciertos casos (no todos) las ballestas no hacen hitmark con el player permitiendole avanzar sin sufrir daño.

Video: [https://drive.google.com/file/d/1gPAnpli43GmwwxglVR7FbTEQWONCjByk/view?usp=sharing](url)

**Comment by santiagosaied** [comment]
Bug a actualizar una vez que descubra cual es el causante de ello.

**Comment by SlayerWx** [comment]
Gracias por tu ayuda!
si entiendo bien, lo que a veces no hace hitmark es el proyectil de la ballesta, cierto?
puede que sea un problema que sea causado por lo pequeño del propio collider pero si el player estuviese quieto en el sitio de hit, debería afectarle.. este bug pasa cuando te moves o cuando estas quieto?

**Comment by santiagosaied** [comment]
> Gracias por tu ayuda!
> si entiendo bien, lo que a veces no hace hitmark es el proyectil de la ballesta, cierto?
> puede que sea un problema que sea causado por lo pequeño del propio collider pero si el player estuviese quieto en el sitio de hit, debería afectarle.. este bug pasa cuando te moves o cuando estas quieto?

Como va? esto ocurre tanto caminando como quieto, en el video no se si se ve quise pararme justo donde deberia hacer hit, pero ignora completamente el collider. Tal vez agrandando un poquito lateralmente donde puede hacer contacto el cupero del player se solucionaria.

Saludos!

**Comment by SlayerWx** [comment]
bien gracias! y usted?, el link al video parece roto, tal vez no están los permisos públicos para poder verlo.. pero probare lo que me estas diciendo y agrandare el collider, espero no vuelva a pasar pero si sigue sucediendo no dudes en decirlo, Muchas Gracias!

**Comment by santiagosaied** [comment]
Te aviso que el Bug ya no ocurre!
