### ISSUE TITLE
TamanoCollider 

### ISSUE THREAD

**Issue by josmar37** [SlayerWx/Fox-s-Tale#4]
TamanoCollider (Game design): Tamaño del collider es grande en compensación del tamaño del escenario. Perdiendo la sensación de espacio dentro del juego.
• En Vista Scene
• Seleccionar el personaje.

Sugerencia (queda a predisposición del desarrollador): achica el collider del personaje y usar una sobrexposición de colliders. 
• El collider más chico (debe estar siempre activo, un simple cuadrado) será de desplazamiento.
• El collider más grande (debe estar desactivado) el contenedor de la figura, cambiara los estados de movimiento. 

Enlace: https://drive.google.com/file/d/1SE5NrBQPTWGB10Oh5BJAJrv0FfMeJOHC/view?usp=sharing

**Comment by SlayerWx** [comment]
actualmente el collider del player es mas pequeño y el collider del mapa esta mejor delimitado, el bug que aparece en el enlace parece estar solucionado aunque no estoy seguro al 100%, si sigues experimentando este bug no dudes en volver a abrir el hilo!
Muchas Gracias!
