### ISSUE TITLE
PausaPlay

### ISSUE THREAD

**Issue by josmar37** [SlayerWx/Fox-s-Tale#5]
PausaPlay: Error en el menu (scene).
• Project / Seleccionar Menu 

Sugerencia (queda a predisposición del desarrollador): achicar el RectTransform. A medidas de los botones.

Enlace: https://drive.google.com/file/d/1J2yOpqPJ4JLSjOwTr-YXWwcdikiPybs8/view?usp=sharing

**Comment by SlayerWx** [comment]
Gracias por la ayuda!
en futuras Builds estará corregido!
