### ISSUE TITLE
PozoSuelo

### ISSUE THREAD

**Issue by josmar37** [SlayerWx/Fox-s-Tale#6]
PozoSuelo: Error en la animación del suelo, se vuelve a reproducir. 
• Assets / Sprite / Trap / BrokenFloor / Anim. suelo roto

Sugerencia (queda a predisposición del desarrollador): detener la animación una vez activado por el collider. Poner un condicional que ya se pasó por encima, para evitar que vuelva a iniciar la animación, así se permite que el collider siga activo. 

Enlace: https://drive.google.com/file/d/1m3qdWXiqrojTWe4rUqEFw6OVe1utSA0b/view?usp=sharing

**Comment by SlayerWx** [comment]
Arreglado! gracias por la ayuda, en el siguiente build ya no estará, el video sirvió bastante.
si notas algún otro bug o que este se repite de alguna forma, por favor avisa nuevamente!

**Comment by josmar37** [comment]
Hola, ¿Cómo estás?, te quería pedir un contacto contigo, correo, cel. que tengas y si no te es mucha molestia. 
Pedirte unas pautas.
•	¿Que se esperan dentro del juego? 
•	¿Cuál es el objetivo principal y secundario?
•	¿Hay alguna trama dentro del juego?
•	¿Qué tipo de juego es? ¿Cuáles buscas llegar?
•	Alguna documentación, que tengas.
