### ISSUE TITLE
Informacion

### ISSUE THREAD

**Issue by josmar37** [SlayerWx/Fox-s-Tale#7]
Hola, ¿Cómo estás?, te quería pedir un contacto contigo, correo, cel. que tengas y si no te es mucha molestia.
Pedirte unas pautas.
• ¿Que se esperan dentro del juego?
• ¿Cuál es el objetivo principal y secundario?
• ¿Hay alguna trama dentro del juego?
• ¿Qué tipo de juego es? ¿Cuáles buscas llegar?
• Alguna documentación, que tengas.

**Comment by SlayerWx** [comment]
Claro!, perdón la demora.. te paso mi Celular para comunicarnos por whatsapp si te parece: 1161930558 y lo hablamos mejor por ahi
