### ISSUE TITLE
WispSpriteRenderer

### ISSUE THREAD

**Issue by josmar37** [SlayerWx/Fox-s-Tale#8]
Se produce al crear muchos wisp a medida que se avanza por el juego.

•	Avanzar por el escenario
•	Se crean los wisp, sin control.
•	Detenerse, se empiezan a alejar.
•	Al volver a retornar el camino.
•	Produce el error al destruir el objeto en cantidad. 

Enlace:  https://drive.google.com/file/d/11qDr1e5d9xEbqKf2ygFqiRZ7K6HE74y_/view?usp=sharing

**Comment by SlayerWx** [comment]
Gracias! si, el proceso que hacen los wisp tenia pensado que sea ese aunque igualmente cuando te persigue la sombra no tenes tanto tiempo para quedarte quieto.. pero creo haber arreglado el error al destruir el objeto! ademas de que ahora los wisp tienen un limite de 10 max
