### ISSUE TITLE
[Textures] Sectores Seguros incorrectos. V1.2

### ISSUE THREAD

**Issue by santiagosaied** [SlayerWx/Fox-s-Tale#9]
Como la anterior vez sigue ocurriendo que hay sectores donde sigue siendo seguro cuando no deberia.

Por ahora solo ocurre en las intersecciones en forma de T. Seguire probando otras partes para corroborar

https://drive.google.com/file/d/1AO_HdWbsamgIYdPgpSQ0YfKKaxlyjzbS/view?usp=sharing

**Comment by SlayerWx** [comment]
muchas gracias! parece que tendré que ponerme mas serio con este problema!
